# Site settings
title: SQUAD - reshelf - recycle, reuse, reduce 
description: 'The reshelf project. Part of SQUAD @ inno.space Mannheim'
url: 'https://mormundhs-ma.github.io/reshelf-instructions/'
baseurl: '/reshelf-instructions'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  joshgerdes
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
